{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "  warnings.warn(\n",
      "/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\n",
      "\tgeopandas.options.use_pygeos = True\n",
      "\n",
      "If you intended to use PyGEOS, set the option to False.\n",
      "  _check_geopandas_using_shapely()\n",
      "/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "import ark\n",
    "import spatialdata as sd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "sdata = sd.read_zarr(store=\"../data/cohorts/example_cohort.ome.zarr/\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-09-02 17:15:05,735\tINFO worker.py:1612 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265 \u001b[39m\u001b[22m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-126893b3-fd56-48bd-b952-ba7b56757076 pid=97857)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-126893b3-fd56-48bd-b952-ba7b56757076 pid=97857)\u001b[0m   warnings.warn(\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3b183d4a-0795-4c12-82f0-551321eb327d pid=97862)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3b183d4a-0795-4c12-82f0-551321eb327d pid=97862)\u001b[0m \n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3b183d4a-0795-4c12-82f0-551321eb327d pid=97862)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3b183d4a-0795-4c12-82f0-551321eb327d pid=97862)\u001b[0m \n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3b183d4a-0795-4c12-82f0-551321eb327d pid=97862)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3b183d4a-0795-4c12-82f0-551321eb327d pid=97862)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-44dcf4b4-8881-47ec-bef7-298920a0cbcc pid=97866)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-44dcf4b4-8881-47ec-bef7-298920a0cbcc pid=97866)\u001b[0m Perhaps you already have a cluster running?\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-44dcf4b4-8881-47ec-bef7-298920a0cbcc pid=97866)\u001b[0m Hosting the HTTP server on port 64068 instead\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-62b17b64-d220-47d3-a871-d71bbb562331 pid=97860)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-cff802a7-767b-4d81-ad68-7a8ef2be7b31 pid=97864)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\u001b[32m [repeated 9x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-62b17b64-d220-47d3-a871-d71bbb562331 pid=97860)\u001b[0m   warnings.warn(\u001b[32m [repeated 20x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-cff802a7-767b-4d81-ad68-7a8ef2be7b31 pid=97864)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-cff802a7-767b-4d81-ad68-7a8ef2be7b31 pid=97864)\u001b[0m \u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-cff802a7-767b-4d81-ad68-7a8ef2be7b31 pid=97864)\u001b[0m \tgeopandas.options.use_pygeos = True\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-cff802a7-767b-4d81-ad68-7a8ef2be7b31 pid=97864)\u001b[0m If you intended to use PyGEOS, set the option to False.\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-cff802a7-767b-4d81-ad68-7a8ef2be7b31 pid=97864)\u001b[0m   _check_geopandas_using_shapely()\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-3c8d4a08-723d-4769-bc36-290fd84f16f7 pid=97858)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-3c8d4a08-723d-4769-bc36-290fd84f16f7 pid=97858)\u001b[0m Perhaps you already have a cluster running?\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-3c8d4a08-723d-4769-bc36-290fd84f16f7 pid=97858)\u001b[0m Hosting the HTTP server on port 64170 instead\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-3c8d4a08-723d-4769-bc36-290fd84f16f7 pid=97858)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m   warnings.warn(\u001b[32m [repeated 11x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m \u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m \tgeopandas.options.use_pygeos = True\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m If you intended to use PyGEOS, set the option to False.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m   _check_geopandas_using_shapely()\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-086e2d2c-8089-421c-b8c0-70ec0755baf0 pid=98063)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-086e2d2c-8089-421c-b8c0-70ec0755baf0 pid=98063)\u001b[0m Perhaps you already have a cluster running?\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-086e2d2c-8089-421c-b8c0-70ec0755baf0 pid=98063)\u001b[0m Hosting the HTTP server on port 64647 instead\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:_get_single_compartment_props-e2b51962-b35a-47cf-8fb3-0d9b194efac5 pid=98072)\u001b[0m   warnings.warn(\u001b[32m [repeated 5x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m \u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m Perhaps you already have a cluster running?\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m Hosting the HTTP server on port 64790 instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-937d5104-c075-44d0-a4b2-fd1cf435fb97 pid=97864)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/_core/operations/aggregate.py:244: UserWarning: Converting `region_key: region` to categorical dtype.\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-937d5104-c075-44d0-a4b2-fd1cf435fb97 pid=97864)\u001b[0m   table = TableModel.parse(table, region=shapes_name, region_key=region_key, instance_key=instance_key)\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m   warnings.warn(\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m \u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-81179e20-4c06-4b0b-ae28-ff41932c693c pid=97859)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/_core/operations/aggregate.py:244: UserWarning: Converting `region_key: region` to categorical dtype.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-81179e20-4c06-4b0b-ae28-ff41932c693c pid=97859)\u001b[0m   table = TableModel.parse(table, region=shapes_name, region_key=region_key, instance_key=instance_key)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m Perhaps you already have a cluster running?\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m Hosting the HTTP server on port 64959 instead\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m   warnings.warn(\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m \u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-b4bb5c9d-9538-4fd9-bd65-f1baa89a7f81 pid=98083)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-feb32a08-7d24-4cf6-84d9-23d1cfceb9f3 pid=97858)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/_core/operations/aggregate.py:244: UserWarning: Converting `region_key: region` to categorical dtype.\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-feb32a08-7d24-4cf6-84d9-23d1cfceb9f3 pid=97858)\u001b[0m   table = TableModel.parse(table, region=shapes_name, region_key=region_key, instance_key=instance_key)\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m Perhaps you already have a cluster running?\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-a5af8a58-7977-4fba-aeff-96fb9299a56f pid=98117)\u001b[0m Hosting the HTTP server on port 65059 instead\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m Perhaps you already have a cluster running?\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m Hosting the HTTP server on port 65123 instead\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c13042f0-a237-49bf-8de6-33abdd70e000 pid=98190)\u001b[0m   warnings.warn(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m \u001b[32m [repeated 8x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-f9f19f96-b5cb-433b-9708-d08cedb27504 pid=98169)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m \tgeopandas.options.use_pygeos = True\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m If you intended to use PyGEOS, set the option to False.\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m   _check_geopandas_using_shapely()\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-768488be-c661-4117-a9f1-e9012e1514d4 pid=97860)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/_core/operations/aggregate.py:244: UserWarning: Converting `region_key: region` to categorical dtype.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-768488be-c661-4117-a9f1-e9012e1514d4 pid=97860)\u001b[0m   table = TableModel.parse(table, region=shapes_name, region_key=region_key, instance_key=instance_key)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m Perhaps you already have a cluster running?\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m Hosting the HTTP server on port 65202 instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m 2023-09-02 17:15:50,673 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/comm/tcp.py\", line 224, in read\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     frames_nbytes = await stream.read_bytes(fmt_size)\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m tornado.iostream.StreamClosedError: Stream is closed\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m The above exception was the direct cause of the following exception:\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/worker.py\", line 1253, in heartbeat\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     response = await retry_operation(\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/utils_comm.py\", line 454, in retry_operation\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     return await retry(\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m            ^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/utils_comm.py\", line 433, in retry\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     return await coro()\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m            ^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/core.py\", line 1356, in send_recv_from_rpc\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     return await send_recv(comm=comm, op=key, **kwargs)\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/core.py\", line 1115, in send_recv\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     response = await comm.read(deserializers=deserializers)\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/comm/tcp.py\", line 240, in read\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     convert_stream_closed_error(self, e)\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/comm/tcp.py\", line 143, in convert_stream_closed_error\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m     raise CommClosedError(f\"in {obj}: {exc}\") from exc\n",
      "\u001b[2m\u001b[36m(dask:('assign-09da5dd097e1733fe38e4451ebdb0635', 0) pid=97866)\u001b[0m distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:64424 remote=tcp://127.0.0.1:64075>: Stream is closed\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-cf11c835-b729-4da0-b394-8249c537e708 pid=98061)\u001b[0m   warnings.warn(\u001b[32m [repeated 7x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m \u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_generate_fov_table-887f42bf-2f36-41f4-a5e1-949474d62aa8 pid=98203)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m Perhaps you already have a cluster running?\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-c7fd976b-79c4-471d-a9c5-17f58b776537 pid=98200)\u001b[0m Hosting the HTTP server on port 65288 instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/_core/operations/aggregate.py:244: UserWarning: Converting `region_key: region` to categorical dtype.\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-ad122e86-b41f-4c55-8de0-bf7cce4b013f pid=98073)\u001b[0m   table = TableModel.parse(table, region=shapes_name, region_key=region_key, instance_key=instance_key)\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m   _check_geopandas_using_shapely()\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m 2023-09-02 17:15:51,280 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m Traceback (most recent call last):\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/comm/tcp.py\", line 240, in read\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     frames_nbytes = await stream.read_bytes(fmt_size)\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m tornado.iostream.StreamClosedError: Stream is closed\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m The above exception was the direct cause of the following exception:\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/worker.py\", line 1253, in heartbeat\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     response = await retry_operation(\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/utils_comm.py\", line 454, in retry_operation\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     return await retry(\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m            ^^^^^^^^^^^^\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/utils_comm.py\", line 433, in retry\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     return await coro()\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/core.py\", line 1356, in send_recv_from_rpc\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     return await send_recv(comm=comm, op=key, **kwargs)\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/core.py\", line 1115, in send_recv\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     response = await comm.read(deserializers=deserializers)\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     convert_stream_closed_error(self, e)\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m   File \"/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/comm/tcp.py\", line 143, in convert_stream_closed_error\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m     raise CommClosedError(f\"in {obj}: {exc}\") from exc\n",
      "\u001b[2m\u001b[36m(dask:finalize-15066ea5-eb42-4111-80c8-806e1fb347da pid=98169)\u001b[0m distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:65223 remote=tcp://127.0.0.1:65128>: Stream is closed\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m   warnings.warn(\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m \u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-a8a04b40-b927-432a-b9aa-b6b0fbf4e495 pid=98260)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/dask/config.py:694: UserWarning: Configuration key \"shuffle\" has been deprecated. Please use \"dataframe.shuffle.algorithm\" instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m Perhaps you already have a cluster running?\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m Hosting the HTTP server on port 65439 instead\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3e3a7116-6305-4291-a82a-fed212e2f7e0 pid=97863)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/_core/operations/aggregate.py:244: UserWarning: Converting `region_key: region` to categorical dtype.\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:_compute_marker_counts-3e3a7116-6305-4291-a82a-fed212e2f7e0 pid=97863)\u001b[0m   table = TableModel.parse(table, region=shapes_name, region_key=region_key, instance_key=instance_key)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m /Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m \tgeopandas.options.use_pygeos = True\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m If you intended to use PyGEOS, set the option to False.\n",
      "\u001b[2m\u001b[36m(dask:regionprops_df-ee678ee3-e406-4b88-91c4-8e59214d4163 pid=98328)\u001b[0m   _check_geopandas_using_shapely()\n"
     ]
    }
   ],
   "source": [
    "f = sdata.marker_quantification.generate_cell_table()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov0_whole_cell': SpatialImage[yx] (512, 512)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 1056 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (1056, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov0', with elements:\n",
       "         fov0_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov1_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 1903 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (1903, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov1', with elements:\n",
       "         fov1_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov2_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 3376 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (3376, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov2', with elements:\n",
       "         fov2_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov3_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 3017 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (3017, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov3', with elements:\n",
       "         fov3_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov4_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 2693 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (2693, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov4', with elements:\n",
       "         fov4_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov5_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 2815 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (2815, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov5', with elements:\n",
       "         fov5_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov6_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 3467 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (3467, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov6', with elements:\n",
       "         fov6_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov7_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 1950 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (1950, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov7', with elements:\n",
       "         fov7_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov8_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 4929 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (4929, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov8', with elements:\n",
       "         fov8_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov9_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 2646 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (2646, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov9', with elements:\n",
       "         fov9_whole_cell (Labels),\n",
       " SpatialData object with:\n",
       " ├── Labels\n",
       " │     └── 'fov10_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       " └── Table\n",
       "       └── AnnData object with n_obs × n_vars = 4225 × 22\n",
       "     obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "     uns: 'spatialdata_attrs': AnnData (4225, 22)\n",
       " with coordinate systems:\n",
       " ▸ 'fov10', with elements:\n",
       "         fov10_whole_cell (Labels)]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.\n",
      "  warnings.warn(\"Transforming to str index.\", ImplicitModificationWarning)\n",
      "/Users/srivarra/.pyenv/versions/3.11.4/envs/ark-spatial/lib/python3.11/site-packages/anndata/_core/anndata.py:1838: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.\n",
      "  utils.warn_names_duplicates(\"obs\")\n"
     ]
    }
   ],
   "source": [
    "g = sd.concatenate(f, region_key=\"region\", instance_key=\"instance_id\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "AnnData object with n_obs × n_vars = 32077 × 22\n",
       "    obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "    uns: 'spatialdata_attrs'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "g.table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "sdata.table = g.table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "del sdata.table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "SpatialData object with:\n",
       "├── Images\n",
       "│     ├── 'fov0': SpatialImage[cyx] (22, 512, 512)\n",
       "│     ├── 'fov1': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov2': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov3': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov4': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov5': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov6': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov7': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov8': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     ├── 'fov9': SpatialImage[cyx] (22, 1024, 1024)\n",
       "│     └── 'fov10': SpatialImage[cyx] (22, 1024, 1024)\n",
       "├── Labels\n",
       "│     ├── 'fov0_nuclear': SpatialImage[yx] (512, 512)\n",
       "│     ├── 'fov0_whole_cell': SpatialImage[yx] (512, 512)\n",
       "│     ├── 'fov1_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov1_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov2_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov2_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov3_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov3_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov4_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov4_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov5_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov5_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov6_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov6_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov7_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov7_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov8_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov8_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov9_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov9_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "│     ├── 'fov10_nuclear': SpatialImage[yx] (1024, 1024)\n",
       "│     └── 'fov10_whole_cell': SpatialImage[yx] (1024, 1024)\n",
       "└── Table\n",
       "      └── AnnData object with n_obs × n_vars = 32077 × 22\n",
       "    obs: 'instance_id', 'centroid-0', 'centroid-1', 'area_convex', 'equivalent_diameter', 'axis_major_length', 'perimeter', 'eccentricity', 'area', 'axis_minor_length', 'major_minor_axis_ratio', 'perim_square_over_area', 'major_axis_equiv_diam_ratio', 'convex_hull_equiv_diam_ratio', 'centroid_dif', 'num_concavities', 'region'\n",
       "    uns: 'spatialdata_attrs': AnnData (32077, 22)\n",
       "with coordinate systems:\n",
       "▸ 'fov0', with elements:\n",
       "        fov0 (Images), fov0_nuclear (Labels), fov0_whole_cell (Labels)\n",
       "▸ 'fov1', with elements:\n",
       "        fov1 (Images), fov1_nuclear (Labels), fov1_whole_cell (Labels)\n",
       "▸ 'fov2', with elements:\n",
       "        fov2 (Images), fov2_nuclear (Labels), fov2_whole_cell (Labels)\n",
       "▸ 'fov3', with elements:\n",
       "        fov3 (Images), fov3_nuclear (Labels), fov3_whole_cell (Labels)\n",
       "▸ 'fov4', with elements:\n",
       "        fov4 (Images), fov4_nuclear (Labels), fov4_whole_cell (Labels)\n",
       "▸ 'fov5', with elements:\n",
       "        fov5 (Images), fov5_nuclear (Labels), fov5_whole_cell (Labels)\n",
       "▸ 'fov6', with elements:\n",
       "        fov6 (Images), fov6_nuclear (Labels), fov6_whole_cell (Labels)\n",
       "▸ 'fov7', with elements:\n",
       "        fov7 (Images), fov7_nuclear (Labels), fov7_whole_cell (Labels)\n",
       "▸ 'fov8', with elements:\n",
       "        fov8 (Images), fov8_nuclear (Labels), fov8_whole_cell (Labels)\n",
       "▸ 'fov9', with elements:\n",
       "        fov9 (Images), fov9_nuclear (Labels), fov9_whole_cell (Labels)\n",
       "▸ 'fov10', with elements:\n",
       "        fov10 (Images), fov10_nuclear (Labels), fov10_whole_cell (Labels)\n",
       "▸ 'global', with elements:\n",
       "        fov0 (Images), fov1 (Images), fov2 (Images), fov3 (Images), fov4 (Images), fov5 (Images), fov6 (Images), fov7 (Images), fov8 (Images), fov9 (Images), fov10 (Images)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sdata"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ark-spatial",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
